package com.maxidev.wallsplash.feature.detail.domain.model

data class PhotoDetail(
    val id: String,
    val width: Int,
    val height: Int,
    val color: String,
    val blurHash: String,
    val altDescription: String,
    val likes: Int,
    val views: Int,
    val downloads: Int,
    val imageRaw: String,
    val imageFull: String,
    val imageRegular: String,
    val imageSmall: String,
    val imageThumb: String,
    val userId: String,
    val username: String,
    val name: String,
    val userProfileImage: String,
    val userLink: String,
    val exifMake: String,
    val exifModel: String,
    val exifName: String,
    val exifExposureTime: String,
    val exifAperture: String,
    val exifFocalLength: String,
    val exifIso: Int,
    val locationCity: String,
    val locationCountry: String,
    val locationPositionLatitude: Double,
    val locationPositionLongitude: Double,
    val tags: List<String>
)