package com.maxidev.wallsplash.feature.detail.presentation.model

data class PhotoDetailUi(
    val id: String,
    val width: Int,
    val height: Int,
    val dimensions: String,
    val color: String,
    val blurHash: String,
    val altDescription: String,
    val likes: String,
    val views: String,
    val downloads: String,
    val imageRaw: String,
    val imageFull: String,
    val imageRegular: String,
    val imageSmall: String,
    val imageThumb: String,
    val userId: String,
    val username: String,
    val name: String,
    val userProfileImage: String,
    val userLink: String,
    val exifMake: String,
    val exifModel: String,
    val exifName: String,
    val exifExposureTime: String,
    val exifAperture: String,
    val exifFocalLength: String,
    val exifIso: String,
    val locationName: String,
    val locationPositionLatitude: String,
    val locationPositionLongitude: String,
    val tags: List<String>
)